name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu,x86_64-pc-windows-gnu,x86_64-apple-darwin,aarch64-apple-darwin
          
      - name: Install cross-compilation dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-mingw-w64-x86-64
          
      - name: Build for Linux
        run: cargo build --release --target x86_64-unknown-linux-gnu
        
      - name: Build for Windows
        run: cargo build --release --target x86_64-pc-windows-gnu
        
      - name: Build for macOS Intel
        run: cargo build --release --target x86_64-apple-darwin
        
      - name: Build for macOS ARM
        run: cargo build --release --target aarch64-apple-darwin
        
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/x86_64-unknown-linux-gnu/release/obscura
            target/x86_64-pc-windows-gnu/release/obscura.exe
            target/x86_64-apple-darwin/release/obscura
            target/aarch64-apple-darwin/release/obscura
          generate_release_notes: true